---
version: "2.4"
services:
  nginx-server:
    build: .
    networks:
      - nginx

    healthcheck:
      test: ["CMD", "ansible-playbook", "upstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  nginx:
