---
version: "2.4"
services:
  app:
    image: penguintech/nginx
    build: .
    ports:
      - "180:80"
      - "443:443"
    networks:
      - nginx
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  nginx:
